<a href="https://colab.research.google.com/github/AbubekerMohammed/ToledoExcelModules/blob/main/TSP_with_AI_parallelism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import requests
import random
import math
import time
import itertools
import folium
import multiprocessing as mp
from IPython.display import IFrame
import os
# Set your Google Maps API key here securely
API_KEY = "AIzaSyARzIP_CHSgaWdWziGWZURVoPOTmHQzRTM"

# Function to get coordinates of a city using Google Maps Geocoding API
def get_coordinates(city):
    try:
        response = requests.get(f"https://maps.googleapis.com/maps/api/geocode/json?address={city}&key={API_KEY}")
        data = response.json()
        if data.get('status') == 'REQUEST_DENIED':
            print(f"Error retrieving coordinates for {city}: {data['error_message']}")
            return None, None
        elif data['status'] == 'OK':
            location = data['results'][0]['geometry']['location']
            return location['lat'], location['lng']
        elif data['status'] == 'ZERO_RESULTS':
            print(f"Error retrieving coordinates for {city}: {data}")
            sys.exit(1)
            return None, None
        else:
            print(f"Error retrieving coordinates for {city}: {data}")
            sys.exit(1)
            return None, None
    except Exception as e:
        print(f"Exception occurred while retrieving coordinates for {city}: {e}")
        return None, None

# Function to get the distance matrix between cities using Google Maps Distance Matrix API
def get_road_distance(origin, destination):
    try:
        response = requests.get(f"https://maps.googleapis.com/maps/api/directions/json?origin={origin}&destination={destination}&key={API_KEY}")
        data = response.json()
        if 'routes' in data and len(data['routes']) > 0 and 'legs' in data['routes'][0] and len(data['routes'][0]['legs']) > 0:
            distance = data['routes'][0]['legs'][0]['distance']['value'] / 1000  # Convert meters to kilometers
            return distance
        else:
            print(f"Error retrieving road distance for {origin} to {destination}: {data}")
            return np.inf
    except Exception as e:
        print(f"Exception occurred while retrieving road distance for {origin} to {destination}: {e}")
        return np.inf

# Function to get road distance matrix between cities
def get_road_distance_matrix(cities):
    n = len(cities)
    matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i != j:
                distance = get_road_distance(cities[i], cities[j])
                matrix[i][j] = distance
                matrix[j][i] = distance
    return matrix

def calculatePath(matrix, path):
    distance = 0
    for i in range(len(path) - 1):
        distance += matrix[path[i]][path[i + 1]]
    return distance

def get_road_directions(origin, destination):
    try:
        response = requests.get(f"https://maps.googleapis.com/maps/api/directions/json?origin={origin}&destination={destination}&key={API_KEY}")
        data = response.json()
        if 'routes' in data and len(data['routes']) > 0 and 'legs' in data['routes'][0] and len(data['routes'][0]['legs']) > 0:
            steps = data['routes'][0]['legs'][0]['steps']
            directions = []
            for step in steps:
                start_loc = step['start_location']
                end_loc = step['end_location']
                directions.append((start_loc['lat'], start_loc['lng']))
                directions.append((end_loc['lat'], end_loc['lng']))
            return directions
        else:
            print(f"Error retrieving road directions for {origin} to {destination}: {data}")
            return []
    except Exception as e:
        print(f"Exception occurred while retrieving road directions for {origin} to {destination}: {e}")
        return []
def plot_on_map(coords):
    avg_lat = np.mean([coords[i][0] for i in range(len(coords))])
    avg_lng = np.mean([coords[i][1] for i in range(len(coords))])

    m = folium.Map(location=[avg_lat, avg_lng], zoom_start=12)

    # Add markers for each city
    for i in range(len(coords)):
        folium.Marker([coords[i][0], coords[i][1]], popup=str(i)).add_to(m)

    # Save the map as an HTML file
    m.save('tsp_unmarked_map.html')

def plot_path_on_map(coords, path):
    avg_lat = np.mean([coords[i][0] for i in range(len(coords))])
    avg_lng = np.mean([coords[i][1] for i in range(len(coords))])

    m = folium.Map(location=[avg_lat, avg_lng], zoom_start=12)

    # Add markers for each city
    for i in range(len(coords)):
        folium.Marker([coords[i][0], coords[i][1]], popup=str(i)).add_to(m)

    # Plot the path using road directions
    for i in range(len(path) - 1):
        origin = cities[path[i]]
        destination = cities[path[i + 1]]
        directions = get_road_directions(origin, destination)
        folium.PolyLine(locations=directions, color="blue", weight=2.5, opacity=1).add_to(m)
        if directions:
            folium.PolyLine(locations=directions, color="blue", weight=2.5, opacity=1).add_to(m)

    # Save the map as an HTML file
    m.save('tsp_solution_map.html')

def simulatedAnnealing(matrix, start_city, coords, initial_temp=1000, cooling_rate=0.995, min_temp=1e-3, num_runs=10, save_plots=False):
    n = len(matrix)
    best_path = None
    best_distance = float('inf')
    steps = 0

    current_path = [start_city] + random.sample([i for i in range(n) if i != start_city], n - 1)
    current_distance = calculatePath(matrix, current_path)
    temp = initial_temp

    while temp > min_temp:
        new_path = current_path[:]
        i, j = random.sample(range(1, n), 2)
        new_path[i], new_path[j] = new_path[j], new_path[i]
        new_distance = calculatePath(matrix, new_path)
        steps += 1

        if new_distance < current_distance or random.uniform(0, 1) < math.exp((current_distance - new_distance) / temp):
            current_path = new_path
            current_distance = new_distance

            if current_distance < best_distance:
                best_path = current_path
                best_distance = current_distance

        temp *= cooling_rate

    if save_plots:
        plot_path_on_map(coords, best_path)

    return best_path, best_distance, steps

def worker(matrix, start_city, return_dict, coords, initial_temp, cooling_rate, min_temp, num_runs, save_plots):
    best_path, best_distance, steps = simulatedAnnealing(matrix, start_city, coords, initial_temp, cooling_rate, min_temp, num_runs, save_plots)
    return_dict[start_city] = (best_path, best_distance, steps)

def multiProcessTSP(matrix, coords, initial_temp=1000, cooling_rate=0.995, min_temp=1e-3, num_runs=10, save_plots=False, processors=None):
    if processors is None:
        processors = mp.cpu_count()
    manager = mp.Manager()
    return_dict = manager.dict()

    with mp.Pool(processes=processors) as pool:
        for start_city in range(len(matrix)):
            pool.apply_async(worker, args=(matrix, start_city, return_dict, coords, initial_temp, cooling_rate, min_temp, num_runs, save_plots))

        pool.close()
        pool.join()

    best_start_city = None
    best_distance = float('inf')
    best_path = None
    total_steps = 0

    for start_city, (path, distance, steps) in return_dict.items():
        if distance < best_distance:
            best_distance = distance
            best_start_city = start_city
            best_path = path
        total_steps += steps

    return best_start_city, best_path, best_distance, total_steps

def brute_force_tsp(matrix, coords):
    num_cities = len(matrix)
    best_distance = float('inf')
    best_path = None

    all_permutations = itertools.permutations(range(num_cities))

    for path in all_permutations:
        distance = calculatePath(matrix, path)
        if distance < best_distance:
            best_distance = distance
            best_path = path

    return best_distance, best_path

# List of cities
cities = ["2 Hippo Way, Toledo, OH 43609", "1744 N Westwood Ave, Toledo, OH 43607", "1440 Secor Rd Ste 120 J Ste 120J, Toledo, OH 43606", "4625 W Bancroft St, Toledo, OH 43615", "2445 Monroe St, Toledo, OH 43620", "3000 Arlington Ave, Toledo, OH 43614"]

# Get coordinates for the cities
coords = []
for city in cities:
    lat, lon = get_coordinates(city)
    if lat is not None and lon is not None:
        coords.append((lat, lon))
    else:
        print(f"Failed to retrieve coordinates for {city}")
        exit(1)
coords = np.array(coords)

# Get distances and coordinates for the cities
matrix = get_road_distance_matrix(cities)
plot_on_map(coords)
# Method Selection
print("Choose method:")
print("1. Simulated Annealing with Parallelism")
print("2. Simulated Annealing (Loop through all cities)")
print("3. Brute Force")
print("4. Run all methods")
choice = int(input("Enter the number of your choice: "))

if choice in [1, 4]:
    initial_temp = 1000
    cooling_rate = 0.995
    min_temp = 1e-3
    num_runs = 10
    start_time_1 = time.time()
    best_start_city, best_path, best_distance, total_steps = multiProcessTSP(matrix, coords, initial_temp, cooling_rate, min_temp, num_runs, save_plots=True)
    stop_time_1 = time.time()
    city_names_path = [cities[i] for i in best_path]
    print(f"Best path (Simulated Annealing with Parallelism): {city_names_path}")
    print(f"Total steps taken: {total_steps}")
    print(f"Total distance: {best_distance} km")
    print(f"Time taken: {stop_time_1 - start_time_1} seconds")

if choice in [2, 4]:
    start_time_2 = time.time()
    initial_temp = 1000
    cooling_rate = 0.995
    min_temp = 1e-3
    num_runs = 10
    best_distance_2 = float('inf')
    best_path_2 = None
    total_steps_2 = 0

    for start_city in range(len(matrix)):
        best_path, best_distance, steps = simulatedAnnealing(matrix, start_city, coords, initial_temp, cooling_rate, min_temp, num_runs)
        total_steps_2 += steps
        if best_distance < best_distance_2:
            best_distance_2 = best_distance
            best_path_2 = best_path

    stop_time_2 = time.time()
    city_names_path_2 = [cities[i] for i in best_path_2]
    print(f"Best path (Simulated Annealing loop through all cities): {city_names_path_2}")
    print(f"Total steps taken: {total_steps_2}")
    print(f"Total distance: {best_distance_2} km")
    print(f"Time taken: {stop_time_2 - start_time_2} seconds")

if choice in [3, 4]:
    start_time_3 = time.time()
    best_distance_3, best_path_3 = brute_force_tsp(matrix, coords)
    stop_time_3 = time.time()
    city_names_path_3 = [cities[i] for i in best_path_3]
    print(f"Best path (Brute Force): {city_names_path_3}")
    print(f"Total distance: {best_distance_3} km")
    print(f"Time taken: {stop_time_3 - start_time_3} seconds")
# Plot the most efficient path on a map
plot_path_on_map(coords, best_path)

# Display the map in the notebook
IFrame(src='tsp_solution_map.html', width=700, height=600)

Choose method:
1. Simulated Annealing with Parallelism
2. Simulated Annealing (Loop through all cities)
3. Brute Force
4. Run all methods
Enter the number of your choice: 1
Best path (Simulated Annealing with Parallelism): ['4625 W Bancroft St, Toledo, OH 43615', '1440 Secor Rd Ste 120 J Ste 120J, Toledo, OH 43606', '1744 N Westwood Ave, Toledo, OH 43607', '2445 Monroe St, Toledo, OH 43620', '2 Hippo Way, Toledo, OH 43609', '3000 Arlington Ave, Toledo, OH 43614']
Total steps taken: 16542
Total distance: 22.233 km
Time taken: 4.570791721343994 seconds


In [ ]:
#V2 without image creation

In [ ]:
import cupy as cp
import numpy as np
import matplotlib.pyplot as plt
import itertools
import imageio.v2 as imageio
import os
from IPython.display import Image, display
import time
import random


distance_kernel_code = '''
extern "C" __global__
void calculate_distances(const int* matrix1, const int* path, int* distances, int n) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n - 1) {
        int city1 = path[idx];
        int city2 = path[idx + 1];
        int matrix_index = city1*n + city2;
        distances[idx] = matrix1[matrix_index];
    }
}
'''
distance_module = cp.RawModule(code=distance_kernel_code)
calculate_distances_kernel = distance_module.get_function('calculate_distances')


def randomMatrix(size, maxDistance):
    matrix = cp.triu(cp.random.randint(1, maxDistance + 1, size=(size, size)), k=1)
    return matrix + matrix.T

def calculatePath(matrix, path):
    path = cp.asarray(path)
    return cp.sum(matrix[path[:-1], path[1:]])

def calculate_path_distance(matrix, path):
    return np.sum([matrix[path[i], path[i + 1]] for i in range(len(path) - 1)])

def generateCircularCoordinates(n, radius=1):
    angles = cp.linspace(0, 2 * cp.pi, n, endpoint=False)
    coords = cp.column_stack((radius * cp.cos(angles), radius * cp.sin(angles)))
    return coords

def calculate_distance(route, distance_matrix):
    n = len(distance_matrix)
    route = cp.asarray(route, dtype=cp.int32)
    distance_matrix = cp.asarray(distance_matrix, dtype=cp.int32)
    distance_matrix=distance_matrix.flatten()
    distances = cp.empty(route.size - 1, dtype=cp.int32)
    block_size = 256
    grid_size = (route.size - 1 + block_size - 1) // block_size

    stream = cp.cuda.Stream()
    with stream:
        calculate_distances_kernel((grid_size,), (block_size,), (distance_matrix, route, distances, n))
        stream.synchronize()

    total_distance = cp.sum(distances).get()
    return total_distance
##################
def plotPath(ax, matrix, path, step, coords):
    n = len(matrix)
    max_separation = cp.max(matrix).get()
    ax.clear()

    coords_np = coords.get() if coords is not None else None

    for i in range(n):
        for j in range(i + 1, n):
            lw = 1 + np.log(matrix[i, j].get()) / np.log(max_separation)
            ax.plot([coords_np[i, 0], coords_np[j, 0]], [coords_np[i, 1], coords_np[j, 1]], 'k-', lw=lw)

    for i in range(len(path) - 1):
        lw = 1 + np.log(matrix[path[i], path[i + 1]].get()) / np.log(max_separation)
        ax.plot([coords_np[path[i], 0], coords_np[path[i + 1], 0]], [coords_np[path[i], 1], coords_np[path[i + 1], 1]], 'r-', lw=lw)

    ax.plot(coords_np[:, 0], coords_np[:, 1], 'bo')
    for i, (x, y) in enumerate(coords_np):
        ax.text(x, y, str(i), color="red", fontsize=14, ha='center', va='center')
    ax.set_title(f"Step {step}, Distance: {cp.asnumpy(calculate_distance(path, matrix)):.2f}")
    ax.set_aspect('equal')

def plot_path(ax, matrix, path, step, coords):
    n = len(matrix)
    max_separation = np.max(matrix)
    ax.clear()

    coords_np = coords

    for i in range(n):
        for j in range(i + 1, n):
            lw = 1 + np.log(matrix[i, j]) / np.log(max_separation)
            ax.plot([coords_np[i, 0], coords_np[j, 0]], [coords_np[i, 1], coords_np[j, 1]], 'k-', lw=lw)

    for i in range(len(path) - 1):
        lw = 1 + np.log(matrix[path[i], path[i + 1]]) / np.log(max_separation)
        ax.plot([coords_np[path[i], 0], coords_np[path[i + 1], 0]], [coords_np[path[i], 1], coords_np[path[i + 1], 1]], 'r-', lw=lw)

    ax.plot(coords_np[:, 0], coords_np[:, 1], 'bo')
    for i, (x, y) in enumerate(coords_np):
        ax.text(x, y, str(i), color="red", fontsize=14, ha='center', va='center')
    ax.set_title(f"Step {step}, Distance: {calculate_path_distance(matrix, path):.2f}")
    ax.set_aspect('equal')
#####################
def parallel_annealing(distance_matrix, initial_temp=1000, cooling_rate=0.995, iterations=2000, save_plots=False, coords=None):
    n_processes = cp.cuda.runtime.getDeviceCount()
    results = []
    for _ in range(n_processes):
        result = simulated_annealing(distance_matrix, initial_temp, cooling_rate, iterations, save_plots, coords, True)
        results.append(result)
    best_route, best_distance, _ = min(results, key=lambda x: x[1])
    steps = results[0][2]
    return best_route, best_distance, steps

def simulated_annealing(distance_matrix, initial_temp=1000, cooling_rate=0.995,iterations=2000, save_plots=False, coords=None, Parallel=False):
    n_cities = len(distance_matrix)
    current_route = cp.arange(n_cities)
    cp.random.shuffle(current_route)
    current_distance = calculate_distance(current_route, distance_matrix)
    best_route = cp.copy(current_route)
    best_distance = current_distance
    temperature = initial_temp
    step = 0

    for i in range(iterations):
        new_route = cp.copy(current_route)
        l, r = cp.sort(cp.random.randint(0, n_cities, size=2))
        new_route[l:r] = new_route[l:r][::-1]
        new_distance = calculate_distance(new_route, distance_matrix)

        if new_distance < current_distance or cp.random.random() < cp.exp((current_distance - new_distance) / temperature):
            current_route, current_distance = new_route, new_distance

        if new_distance < best_distance:
            best_route, best_distance = new_route, new_distance

            if save_plots and step % 2 == 0:
                fig, ax = plt.subplots()
                plotPath(ax, distance_matrix, best_route.get(), step, coords)
                if Parallel:
                    plt.savefig(f"tsp_Parallel_{step}.png")
                else:
                    plt.savefig(f"tsp_notParallel_{step}.png")
                plt.close(fig)
            step += 1

        temperature *= cooling_rate

    return best_route.astype(np.int32), best_distance.astype(np.int32), step

def brute_force_tsp(matrix, coords, save_plots=False):
    num_cities = len(matrix)
    best_distance = float('inf')
    best_path = None
    step = 0
    matrix=matrix.get()
    coords=coords.get()
    all_permutations = itertools.permutations(range(num_cities))

    fig, ax = plt.subplots() if save_plots else (None, None)

    for path in all_permutations:
        distance = calculate_path_distance(matrix, path)
        if distance < best_distance:
            best_distance = distance
            best_path = path
            step += 1

            if save_plots:
                plot_path(ax, matrix, best_path, step, coords)
                plt.savefig(f"tsp_brute_{step}.png")

    if save_plots:
        plt.close(fig)

    return best_distance, best_path, step


# Example Usage
n = 10
Separation = 100
matrix = randomMatrix(n, Separation)
print(matrix)

coords = generateCircularCoordinates(n)
initial_temp = 10000
cooling_rate = 0.95
iterations = 9000
save_plots = True

print("Choose method:")
print("1. Simulated Annealing with Parallelism")
print("2. Simulated Annealing without Parallelism")
print("3. Brute Force")
print("4. Run both Types of Simulated Annealing")
print("5. Run all methods")
choice = int(input("Enter the number of your choice: "))

results = []

if choice in [1, 4, 5]:
    start_Time_1 = time.time()
    best_route, best_distance, steps = parallel_annealing(matrix, initial_temp, cooling_rate, iterations, save_plots, coords)
    stop_Time_1 = time.time()
    results.append({
        'method': "Simulated Annealing with Parallelism",
        'best_path': best_route,
        'best_distance': best_distance,
        'time_taken': stop_Time_1 - start_Time_1,
        'gif_filename': 'tsp_solution_annealing_Parallel.gif',
        'steps': steps,
        'name': 'Parallel'
    })

if choice in [2, 4, 5]:
    start_Time_1 = time.time()
    best_route, best_distance, steps = simulated_annealing(matrix, initial_temp, cooling_rate, iterations, save_plots, coords)
    stop_Time_1 = time.time()
    results.append({
        'method': "Simulated Annealing without Parallelism",
        'best_path': best_route,
        'best_distance': best_distance,
        'time_taken': stop_Time_1 - start_Time_1,
        'gif_filename': 'tsp_solution_annealing.gif',
        'steps': steps,
        'name': 'notParallel'
    })

if choice in [3, 5]:
    start_Time_2 = time.time()
    best_distance, best_path, steps = brute_force_tsp(matrix, coords, save_plots)
    stop_Time_2 = time.time()
    results.append({
        'method': "Brute Force",
        'best_path': best_path,
        'best_distance': best_distance,
        'time_taken': stop_Time_2 - start_Time_2,
        'gif_filename': 'tsp_solution_brute.gif',
        'steps': steps,
        'name': 'brute'
    })

for result in results:
    print(f"\nMethod: {result['method']}")
    print("Best distance:", result['best_distance'])
    print("Best path:", result['best_path'])
    print("Time taken (s):", result['time_taken'])
    print("Steps:", result['steps'])

    if save_plots:
        images = []
        for step in range(result['steps']+2):
            filename = f"tsp_{result['name']}_{step}.png"
            if os.path.exists(filename):
                images.append(imageio.imread(filename))
                os.remove(filename)
        imageio.mimsave(result['gif_filename'], images, fps=2)
        display(Image(filename=result['gif_filename']))


[[  0  65  81 ...   1  15  31]
 [ 65   0  28 ...  60  93   7]
 [ 81  28   0 ... 100  18  22]
 ...
 [  1  60 100 ...   0   3  82]
 [ 15  93  18 ...   3   0  82]
 [ 31   7  22 ...  82  82   0]]
Choose method:
1. Simulated Annealing with Parallelism
2. Simulated Annealing without Parallelism
3. Brute Force
4. Run both Types of Simulated Annealing
5. Run all methods
Enter the number of your choice: 4

Method: Simulated Annealing with Parallelism
Best distance: 3.495e-42
Best path: [36 70 45  2 40 29 71 75 53  5 69 51 62 21 52 99 30 46 11 48 80 81  0 82
 24 61 44 56 39 38 50  3 65 12 86 35  7  8 22 60  4 33 88 49 66 31 87 41
 91 57 16 90 67 79 68 42 54 93 63 58 76 64 55 18 85 14 27 84 59 20 43 72
 34 17 83 15 37 32 77 74 23 25 96 73 19 78 10 47 92  9 26 13 89 95  6 97
 98 94 28  1]
Time taken (s): 9.683786153793335
Steps: 0

Method: Simulated Annealing without Parallelism
Best distance: 3.358e-42
Best path: [81  6 14 15 12  3 35  4 61 79 71 11 18 29 54 95 21 38 25 83 26 65 66 41
 57 90 39 7

In [ ]:
#!pip install imageio
#!pip install folium
#!pip install Basemap
!pip install multiprocessing

In [ ]:
#Slower
import numpy as np
import multiprocessing as mp
import random
import time
import math
import itertools
import matplotlib.pyplot as plt
import imageio.v2
import os
from IPython.display import Image, display

#########

def randomMatrix(size, maxDistance):
    matrix = np.triu(np.random.randint(1, maxDistance + 1, size=(size, size)), k=1)
    return matrix + matrix.transpose()

def calculatePath(matrix, path):
    distance = 0
    for i in range(len(path) - 1):
        distance += matrix[path[i]][path[i + 1]]
    return distance

def generateCircularCoordinates(n, radius=1):
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False)
    coords = np.column_stack((radius * np.cos(angles), radius * np.sin(angles)))
    return coords

def plotPath(ax, matrix, path, step, coords):
    n = len(matrix)
    ax.clear()
    for i in range(n):
        for j in range(i + 1, n):
            ax.plot([coords[i, 0], coords[j, 0]], [coords[i, 1], coords[j, 1]], 'k-', lw=matrix[i, j] / 2)

    for i in range(len(path) - 1):
        ax.plot([coords[path[i], 0], coords[path[i + 1], 0]], [coords[path[i], 1], coords[path[i + 1], 1]], 'r-', lw=matrix[path[i], path[i + 1]] / 2)

    ax.plot(coords[:, 0], coords[:, 1], 'bo')
    for i, (x, y) in enumerate(coords):
        ax.text(x, y, str(i), color="red", fontsize=14, ha='center', va='center')

    ax.set_title(f"Step {step}, Distance: {calculatePath(matrix, path):.2f}")
    ax.set_aspect('equal')

#########
def simulatedAnnealing(matrix, start_city, coords, initial_temp=1000, cooling_rate=0.995, min_temp=1e-3, num_runs=10, save_plots=False):
    n = len(matrix)
    best_path = None
    best_distance = float('inf')
    step = 0
    for _ in range(num_runs):
        current_path = [start_city] + random.sample([i for i in range(n) if i != start_city], n-1)
        current_distance = calculatePath(matrix, current_path)
        temp = initial_temp
        while temp > min_temp:
            new_path = current_path[:]
            i, j = random.sample(range(1, n), 2)
            new_path[i], new_path[j] = new_path[j], new_path[i]
            new_distance = calculatePath(matrix, new_path)

            if new_distance < current_distance or random.uniform(0, 1) < math.exp((current_distance - new_distance) / temp):
                current_path = new_path
                current_distance = new_distance

                if current_distance < best_distance:
                    best_path = current_path
                    best_distance = current_distance
                    if save_plots and step % 2 == 0:
                        fig, ax = plt.subplots()
                        plotPath(ax, matrix, best_path, step, coords)
                        plt.savefig(f"tsp_step_{step}.png")
                        plt.close(fig)
                    step += 1
            temp *= cooling_rate
    return best_path, best_distance, step

#########
def worker(matrix, start_city, return_dict, coords, initial_temp, cooling_rate, min_temp, num_runs, save_plots):
    best_path, best_distance, steps = simulatedAnnealing(matrix, start_city, coords, initial_temp, cooling_rate, min_temp, num_runs, save_plots)
    return_dict[start_city] = (best_path, best_distance, steps)

def multiProcessTSP(matrix, coords, initial_temp=1000, cooling_rate=0.995, min_temp=1e-3, num_runs=10, save_plots=False, processors=None):
    if processors is None:
        processors = mp.cpu_count()
    manager = mp.Manager()
    return_dict = manager.dict()

    with mp.Pool(processes=processors) as pool:
        for start_city in range(len(matrix)):
            pool.apply_async(worker, args=(matrix, start_city, return_dict, coords, initial_temp, cooling_rate, min_temp, num_runs, save_plots))

        pool.close()
        pool.join()

    best_start_city = None
    best_distance = float('inf')
    best_path = None
    total_steps = 0

    for start_city, (path, distance, steps) in return_dict.items():
        if distance < best_distance:
            best_distance = distance
            best_start_city = start_city
            best_path = path
        total_steps += steps

    return best_start_city, best_path, best_distance, total_steps
#########

def brute_force_tsp(matrix, coords, save_plots=False):
    num_cities = len(matrix)
    best_distance = float('inf')
    best_path = None
    step = 0

    all_permutations = itertools.permutations(range(num_cities))

    for path in all_permutations:
        distance = calculatePath(matrix, path)
        if distance < best_distance:
            best_distance = distance
            best_path = path
            if save_plots and step % 2 == 0:
                fig, ax = plt.subplots()
                plotPath(ax, matrix, best_path, step, coords)
                plt.savefig(f"tsp_brute_step_{step}.png")
                plt.close(fig)
            step += 1

    return best_distance, best_path, step

##########

n = 100
Separation = 100
matrix = randomMatrix(n, Separation)
print(matrix)

coords = generateCircularCoordinates(n)
initial_temp = 1000
cooling_rate = 0.995
min_temp = 1e-3
num_runs = 10
save_plots = False

# Choose method
print("Choose method:")
print("1. Simulated Annealing with Parallelism")
print("2. Simulated Annealing (Loop through all cities)")
print("3. Brute Force")
print("4. Run all methods")
#choice = int(input("Enter the number of your choice: "))
choice=1
results = []

if choice in [1, 4]:
    start_Time_1 = time.time()
    best_start_city, best_path, best_distance, steps = multiProcessTSP(matrix, coords, initial_temp, cooling_rate, min_temp, num_runs, save_plots)
    stop_Time_1 = time.time()
    results.append({
        'method': "Simulated Annealing with Parallelism",
        'best_path': best_path,
        'best_distance': best_distance,
        'time_taken': stop_Time_1 - start_Time_1,
        'gif_filename': 'tsp_solution_annealing_parallel.gif'
    })

if choice in [2, 4]:
    start_Time_1 = time.time()
    best_distance = float('inf')
    best_path = None
    steps = 0

    for start_city in range(n):
        path, distance, local_steps = simulatedAnnealing(matrix, start_city, coords, initial_temp, cooling_rate, min_temp, num_runs, save_plots)
        steps += local_steps
        if distance < best_distance:
            best_distance = distance
            best_path = path

    stop_Time_1 = time.time()
    results.append({
        'method': "Simulated Annealing (Loop through all cities)",
        'best_path': best_path,
        'best_distance': best_distance,
        'time_taken': stop_Time_1 - start_Time_1,
        'gif_filename': 'tsp_solution_annealing_all_cities.gif'
    })

if choice in [3, 4]:
    start_Time_2 = time.time()
    best_distance, best_path, steps = brute_force_tsp(matrix, coords, save_plots)
    stop_Time_2 = time.time()
    results.append({
        'method': "Brute Force",
        'best_path': best_path,
        'best_distance': best_distance,
        'time_taken': stop_Time_2 - start_Time_2,
        'gif_filename': 'tsp_solution_brute_force.gif'
    })

def valid_image_file(filename):
    try:
        image = imageio.v2.imread(filename)
        return True
    except Exception as e:
        print(f"Error reading {filename}: {e}")
        return False

for result in results:
    method = result['method']
    best_path = result['best_path']
    best_distance = result['best_distance']
    time_taken = result['time_taken']
    gif_filename = result['gif_filename']
    steps = result.get('steps', 0)

    print(f"Method: {method}")
    print(f"Best Path: {best_path}")
    print(f"Best Distance: {best_distance}")
    print(f"Time taken: {time_taken} seconds")
    if save_plots == True:
        # Create GIF for the chosen method
        with imageio.get_writer(gif_filename, mode='I', duration=0.5) as writer:
            for step in range(0, steps, 2):
                if 'annealing' in gif_filename:
                    filename = f'tsp_step_{step}.png'
                else:
                    filename = f'tsp_brute_step_{step}.png'
                if os.path.exists(filename) and valid_image_file(filename):
                    image = imageio.v2.imread(filename)
                    writer.append_data(image)

        # Cleanup: Remove the temporary image files
        for step in range(0, steps, 2):
            if 'annealing' in gif_filename:
                filename = f'tsp_step_{step}.png'
            else:
                filename = f'tsp_brute_step_{step}.png'
            if os.path.exists(filename):
                os.remove(filename)

        print(f"GIF created: {gif_filename}")
        display(Image(filename=gif_filename))


[[ 0 81 65 ... 68 19 34]
 [81  0 40 ... 60 78 89]
 [65 40  0 ... 14 82 58]
 ...
 [68 60 14 ...  0 72 50]
 [19 78 82 ... 72  0 69]
 [34 89 58 ... 50 69  0]]
Choose method:
1. Simulated Annealing with Parallelism
2. Simulated Annealing (Loop through all cities)
3. Brute Force
4. Run all methods


KeyboardInterrupt: 

In [ ]:
#New
import numpy as np
import random
import time
import math
import itertools
import matplotlib.pyplot as plt
import imageio.v2 as imageio
import os
from IPython.display import Image, display

#########

def randomMatrix(size, maxDistance):
    matrix = np.triu(np.random.randint(1, maxDistance + 1, size=(size, size)), k=1)
    return matrix + matrix.transpose()

def calculatePath(matrix, path):
    distance = 0
    for i in range(len(path) - 1):
        distance += matrix[path[i]][path[i + 1]]
    return distance

def generateCircularCoordinates(n, radius=1):
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False)
    coords = np.column_stack((radius * np.cos(angles), radius * np.sin(angles)))
    return coords

def plotPath(ax, matrix, path, step, coords):
    n = len(matrix)
    max_separation = np.max(matrix)
    ax.clear()
    for i in range(n):
        for j in range(i + 1, n):
            lw = 1 + np.log(matrix[i, j]) / np.log(max_separation)
            ax.plot([coords[i, 0], coords[j, 0]], [coords[i, 1], coords[j, 1]], 'k-', lw=lw)

    for i in range(len(path) - 1):
        lw = 1 + np.log(matrix[path[i], path[i + 1]]) / np.log(max_separation)
        ax.plot([coords[path[i], 0], coords[path[i + 1], 0]], [coords[path[i + 1], 1]], 'r-', lw=lw)

    ax.plot(coords[:, 0], coords[:, 1], 'bo')
    for i, (x, y) in enumerate(coords):
        ax.text(x, y, str(i), color="red", fontsize=14, ha='center', va='center')

    ax.set_title(f"Step {step}, Distance: {calculatePath(matrix, path):.2f}")
    ax.set_aspect('equal')
#########
def calculate_distance(route, distance_matrix):
    return sum(distance_matrix[route[i], route[i + 1]] for i in range(len(route) - 1))

def simulated_annealing(distance_matrix, initial_temp=1000, cooling_rate=0.995, iterations=2000, save_plots=False, coords=None):
    n_cities = len(distance_matrix)
    current_route = list(range(n_cities))
    random.shuffle(current_route)
    current_distance = calculate_distance(current_route, distance_matrix)
    best_route = list(current_route)
    best_distance = current_distance
    temperature = initial_temp
    step = 0

    for i in range(iterations):
        new_route = current_route[:]
        l, r = sorted(random.sample(range(n_cities), 2))
        new_route[l:r] = reversed(new_route[l:r])
        new_distance = calculate_distance(new_route, distance_matrix)

        if new_distance < current_distance or random.random() < np.exp((current_distance - new_distance) / temperature):
            current_route, current_distance = new_route, new_distance

        if new_distance < best_distance:
            best_route, best_distance = new_route, new_distance

            if save_plots and step % 2 == 0:
                fig, ax = plt.subplots()
                plotPath(ax, distance_matrix, best_route, step, coords)
                plt.savefig(f"tsp_step_{step}.png")
                plt.close(fig)
            step += 1

        temperature *= cooling_rate

    return best_route, best_distance, step

def parallel_annealing(distance_matrix, initial_temp=1000, cooling_rate=0.995, iterations=2000, n_processes=8, save_plots=False, coords=None):
    with Pool(n_processes) as pool:
        tasks = [(distance_matrix, initial_temp, cooling_rate, iterations, save_plots, coords) for _ in range(n_processes)]
        results = pool.starmap(simulated_annealing, tasks)

    best_route, best_distance, _ = min(results, key=lambda x: x[1])
    return best_route, best_distance, results

#########

def brute_force_tsp(matrix, coords, save_plots=False):
    num_cities = len(matrix)
    best_distance = float('inf')
    best_path = None
    step = 0

    all_permutations = itertools.permutations(range(num_cities))

    for path in all_permutations:
        distance = calculatePath(matrix, path)
        if distance < best_distance:
            best_distance = distance
            best_path = path
            if save_plots and step % 2 == 0:
                fig, ax = plt.subplots()
                plotPath(ax, matrix, best_path, step, coords)
                plt.savefig(f"tsp_brute_step_{step}.png")
                plt.close(fig)
            step += 1

    return best_distance, best_path, step

def simulated_annealing_for_each_city(distance_matrix, initial_temp=1000, cooling_rate=0.995, iterations=1000, save_plots=False, coords=None):
    n_cities = len(distance_matrix)
    best_distance = float('inf')
    best_route = None
    total_steps = 0

    for start_city in range(n_cities):
        current_route = list(range(n_cities))
        current_route.remove(start_city)
        current_route.insert(0, start_city)
        random.shuffle(current_route[1:])
        route, distance, steps = simulated_annealing(distance_matrix, initial_temp, cooling_rate, iterations, save_plots, coords)
        if distance < best_distance:
            best_distance = distance
            best_route = route
        total_steps += steps

    return best_route, best_distance, total_steps

##########

n = 100
Separation = 100
matrix = randomMatrix(n, Separation)
print(matrix)

coords = generateCircularCoordinates(n)
initial_temp = 1000
cooling_rate = 0.995
min_temp = 1e-3
iterations = 2000
n_processes = cpu_count()
save_plots = False


print("Choose method:")
print("1. Simulated Annealing with Parallelism")
print("2. Simulated Annealing (Loop through all cities)")
print("3. Brute Force")
print("4. Run both Types of Simulated Annealing")
print("5. Run all methods")
choice = int(input("Enter the number of your choice: "))

results = []

if choice in [1, 4, 5]:
    start_Time_1 = time.time()
    best_route, best_distance, steps_results = parallel_annealing(matrix, initial_temp, cooling_rate, iterations, n_processes, save_plots, coords)
    stop_Time_1 = time.time()
    steps = max(steps_results, key=lambda x: x[2])[2]
    results.append({
        'method': "Simulated Annealing with Parallelism",
        'best_path': best_route,
        'best_distance': best_distance,
        'time_taken': stop_Time_1 - start_Time_1,
        'gif_filename': 'tsp_solution_annealing_parallel.gif',
        'steps': steps
    })

if choice in [2, 4, 5]:
    start_Time_1 = time.time()
    best_route, best_distance, steps = simulated_annealing_for_each_city(matrix, initial_temp, cooling_rate, iterations, save_plots, coords)
    stop_Time_1 = time.time()
    results.append({
        'method': "Simulated Annealing (Loop through all cities)",
        'best_path': best_route,
        'best_distance': best_distance,
        'time_taken': stop_Time_1 - start_Time_1,
        'gif_filename': 'tsp_solution_annealing_all_cities.gif',
        'steps': steps
    })

if choice in [3, 5]:
    start_Time_2 = time.time()
    best_distance, best_path, steps = brute_force_tsp(matrix, coords, save_plots)
    stop_Time_2 = time.time()
    results.append({
        'method': "Brute Force",
        'best_path': best_path,
        'best_distance': best_distance,
        'time_taken': stop_Time_2 - start_Time_2,
        'gif_filename': 'tsp_solution_brute.gif',
        'steps': steps
    })

for result in results:
    print(f"Method: {result['method']}")
    print(f"Best Path: {result['best_path']}")
    print(f"Best Distance: {result['best_distance']}")
    print(f"Time Taken: {result['time_taken']:.2f} seconds")
    print(f"Steps: {result['steps']}")
    if save_plots:
        images = []
        for step in range(result['steps']):
            filename = f"tsp_step_{step}.png"
            if os.path.exists(filename):
                images.append(imageio.imread(filename))
                os.remove(filename)

        imageio.mimsave(result['gif_filename'], images, fps=2)
        display(Image(filename=result['gif_filename']))


[[ 0 83 22 ... 63 88 72]
 [83  0 95 ... 24  1 63]
 [22 95  0 ... 27 19 72]
 ...
 [63 24 27 ...  0 97 10]
 [88  1 19 ... 97  0 34]
 [72 63 72 ... 10 34  0]]


NameError: name 'cpu_count' is not defined

In [ ]:
#Faster
import numpy as np
from multiprocessing import Pool, cpu_count
import random
import time
import math
import itertools
import matplotlib.pyplot as plt
import imageio.v2 as imageio
import os
from IPython.display import Image, display

#########

def randomMatrix(size, maxDistance):
    matrix = np.triu(np.random.randint(1, maxDistance + 1, size=(size, size)), k=1)
    return matrix + matrix.transpose()

def calculatePath(matrix, path):
    distance = 0
    for i in range(len(path) - 1):
        distance += matrix[path[i]][path[i + 1]]
    return distance

def generateCircularCoordinates(n, radius=1):
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False)
    coords = np.column_stack((radius * np.cos(angles), radius * np.sin(angles)))
    return coords

def plotPath(ax, matrix, path, step, coords):
    n = len(matrix)
    max_separation = np.max(matrix)
    ax.clear()
    for i in range(n):
        for j in range(i + 1, n):
            lw = 1 + np.log(matrix[i, j]) / np.log(max_separation)
            ax.plot([coords[i, 0], coords[j, 0]], [coords[i, 1], coords[j, 1]], 'k-', lw=lw)

    for i in range(len(path) - 1):
        lw = 1 + np.log(matrix[path[i], path[i + 1]]) / np.log(max_separation)
        ax.plot([coords[path[i], 0], coords[path[i + 1], 0]], [coords[path[i], 1], coords[path[i + 1], 1]], 'r-', lw=lw)

    ax.plot(coords[:, 0], coords[:, 1], 'bo')
    for i, (x, y) in enumerate(coords):
        ax.text(x, y, str(i), color="red", fontsize=14, ha='center', va='center')

    ax.set_title(f"Step {step}, Distance: {calculatePath(matrix, path):.2f}")
    ax.set_aspect('equal')
#########
def calculate_distance(route, distance_matrix):
    return sum(distance_matrix[route[i], route[i + 1]] for i in range(len(route) - 1))

def simulated_annealing(distance_matrix, initial_temp=1000, cooling_rate=0.995, iterations=1000, save_plots=False, coords=None):
    n_cities = len(distance_matrix)
    current_route = list(range(n_cities))
    random.shuffle(current_route)
    current_distance = calculate_distance(current_route, distance_matrix)
    best_route = list(current_route)
    best_distance = current_distance
    temperature = initial_temp
    step = 0

    for i in range(iterations):
        new_route = current_route[:]
        l, r = sorted(random.sample(range(n_cities), 2))
        new_route[l:r] = reversed(new_route[l:r])
        new_distance = calculate_distance(new_route, distance_matrix)

        if new_distance < current_distance or random.random() < np.exp((current_distance - new_distance) / temperature):
            current_route, current_distance = new_route, new_distance

        if new_distance < best_distance:
            best_route, best_distance = new_route, new_distance

            if save_plots and step % 2 == 0:
                fig, ax = plt.subplots()
                plotPath(ax, distance_matrix, best_route, step, coords)
                plt.savefig(f"tsp_step_{step}.png")
                plt.close(fig)
            step += 1

        temperature *= cooling_rate

    return best_route, best_distance, step

def parallel_annealing(distance_matrix, initial_temp=1000, cooling_rate=0.995, iterations=1000, n_processes=4, save_plots=False, coords=None):
    with Pool(n_processes) as pool:
        tasks = [(distance_matrix, initial_temp, cooling_rate, iterations, save_plots, coords) for _ in range(n_processes)]
        results = pool.starmap(simulated_annealing, tasks)

    best_route, best_distance, _ = min(results, key=lambda x: x[1])
    return best_route, best_distance, results

#########

def brute_force_tsp(matrix, coords, save_plots=False):
    num_cities = len(matrix)
    best_distance = float('inf')
    best_path = None
    step = 0

    all_permutations = itertools.permutations(range(num_cities))

    for path in all_permutations:
        distance = calculatePath(matrix, path)
        if distance < best_distance:
            best_distance = distance
            best_path = path
            if save_plots and step % 2 == 0:
                fig, ax = plt.subplots()
                plotPath(ax, matrix, best_path, step, coords)
                plt.savefig(f"tsp_brute_step_{step}.png")
                plt.close(fig)
            step += 1

    return best_distance, best_path, step

##########

n = 1000
Separation = 100
matrix = randomMatrix(n, Separation)
print(matrix)

coords = generateCircularCoordinates(n)
initial_temp = 1000
cooling_rate = 0.995
min_temp = 1e-3
iterations = 1000
n_processes = cpu_count()
save_plots = False


print("Choose method:")
print("1. Simulated Annealing with Parallelism")
print("2. Simulated Annealing")
print("3. Brute Force")
print("4. Run all methods")
choice = int(input("Enter the number of your choice: "))

results = []

if choice in [1, 4]:
    start_Time_1 = time.time()
    best_route, best_distance, steps_results = parallel_annealing(matrix, initial_temp, cooling_rate, iterations, n_processes, save_plots, coords)
    stop_Time_1 = time.time()
    steps = max(steps_results, key=lambda x: x[2])[2]
    results.append({
        'method': "Simulated Annealing with Parallelism",
        'best_path': best_route,
        'best_distance': best_distance,
        'time_taken': stop_Time_1 - start_Time_1,
        'gif_filename': 'tsp_solution_annealing_parallel.gif',
        'steps': steps
    })

if choice in [2, 4]:
    start_Time_1 = time.time()
    best_distance = float('inf')
    best_path = None
    steps = 0

    start_Time_2 = time.time()
    best_route, best_distance, steps = simulated_annealing(matrix, initial_temp, cooling_rate, 4*iterations, save_plots, coords)
    stop_Time_2 = time.time()


    results.append({
        'method': "Simulated Annealing",
        'best_path': best_route,
        'best_distance': best_distance,
        'time_taken': stop_Time_2 - start_Time_2,
        'gif_filename': 'tsp_solution_annealing_all_cities.gif',
        'steps': steps
    })

if choice in [3]:
    start_Time_3 = time.time()
    best_distance, best_path, steps = brute_force_tsp(matrix, coords, save_plots)
    stop_Time_3 = time.time()
    results.append({
        'method': "Brute Force",
        'best_path': best_path,
        'best_distance': best_distance,
        'time_taken': stop_Time_3 - start_Time_3,
        'gif_filename': 'tsp_solution_brute_force.gif',
        'steps': steps
    })

def valid_image_file(filename):
    try:
        image = imageio.imread(filename)
        return True
    except Exception as e:
        print(f"Error reading {filename}: {e}")
        return False

for result in results:
    method = result['method']
    best_path = result['best_path']
    best_distance = result['best_distance']
    time_taken = result['time_taken']
    gif_filename = result['gif_filename']
    steps = result['steps']

    print(f"Method: {method}")
    print(f"Best Path: {best_path}")
    print(f"Best Distance: {best_distance}")
    print(f"Time taken: {time_taken} seconds")
    if save_plots:
        # Create GIF for the chosen method
        with imageio.get_writer(gif_filename, mode='I', duration=0.5) as writer:
            for step in range(0, steps, 2):
                if 'annealing' in gif_filename:
                    filename = f'tsp_step_{step}.png'
                else:
                    filename = f'tsp_brute_step_{step}.png'
                if os.path.exists(filename) and valid_image_file(filename):
                    image = imageio.imread(filename)
                    writer.append_data(image)

        # Cleanup: Remove the temporary image files
        for step in range(0, steps, 2):
            if 'annealing' in gif_filename:
                filename = f'tsp_step_{step}.png'
            else:
                filename = f'tsp_brute_step_{step}.png'
            if os.path.exists(filename):
                os.remove(filename)

        print(f"GIF created: {gif_filename}")
        display(Image(filename=gif_filename))


[[ 0 88 26 ... 53 23 80]
 [88  0 16 ... 61  1 30]
 [26 16  0 ... 42 18 54]
 ...
 [53 61 42 ...  0 50 32]
 [23  1 18 ... 50  0 26]
 [80 30 54 ... 32 26  0]]
Choose method:
1. Simulated Annealing with Parallelism
2. Simulated Annealing
3. Brute Force
4. Run all methods
Enter the number of your choice: 4
Method: Simulated Annealing with Parallelism
Best Path: [357, 971, 688, 121, 360, 690, 374, 847, 9, 746, 580, 870, 581, 248, 753, 369, 814, 928, 735, 904, 15, 208, 112, 252, 556, 869, 245, 88, 36, 529, 92, 251, 997, 573, 839, 572, 711, 879, 464, 177, 510, 893, 851, 232, 318, 133, 786, 548, 495, 463, 727, 276, 559, 484, 32, 886, 331, 199, 433, 541, 859, 877, 415, 778, 512, 439, 999, 311, 544, 334, 620, 450, 557, 390, 269, 215, 606, 865, 85, 290, 939, 347, 365, 754, 912, 0, 106, 700, 456, 674, 388, 667, 350, 96, 650, 454, 819, 866, 885, 474, 571, 710, 705, 682, 982, 141, 770, 80, 394, 5, 986, 187, 247, 767, 991, 703, 434, 140, 467, 692, 424, 546, 683, 278, 951, 599, 49, 273, 503, 195, 769, 